name: context-debias
channels:
  - pytorch
  - defaults
dependencies:
  - apex=0.9.10dev
  - nltk=3.5
  - numpy=1.24.4
  - ptvsd=4.3.2
  - python=3.7.3
  - regex=2023.10.3
  - tensorboard=2.0.2
  - torch=1.5.0
  - tqdm=4.66.1
  - transformers=2.8.0
