name: sent-bias
channels:
  - pytorch
  - defaults
dependencies:
  - hdf5=1.10.4
  - numpy=1.16.2
  - numpy-base=1.16.2
  - pip=19.0.3
  - python=3.6.8
  - pytorch=0.4.1
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - pip:
    - allennlp==0.8.2
    - matplotlib==2.2.3
    - nltk==3.4
    - scikit-learn==0.20.3
    - tensorflow-hub==0.3.0